// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Twenty57.Linx.Components.Pdf.ChangeProtection.Templates
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    internal partial class ChangeProtectionTemplate : ChangeProtectionTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 3 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 
	string readerPropertyName = "reader";
	string stamperPropertyName = "stamper";
	string protectCertificatePropertyName = "protectCertificate";
	string permissionsPropertyName = "permissions";

            
            #line default
            #line hidden
            this.Write("\r\nif (string.IsNullOrEmpty(");
            
            #line 10 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OutputFilePathParameterName));
            
            #line default
            #line hidden
            this.Write("))\r\n\tthrow new ArgumentNullException(\"");
            
            #line 11 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OutputFilePathParameterName));
            
            #line default
            #line hidden
            this.Write("\");\r\n\r\niTextSharp.text.pdf.PdfReader ");
            
            #line 13 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));
            
            #line default
            #line hidden
            this.Write(" = null;\r\ntry\r\n{\r\n");
            
            #line 16 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 
AssignPdfReader(readerPropertyName, InputAuthenticationType, InputFilePathParameterName, InputPasswordParameterName, 
	InputCertificateSource, InputCertificateFilePathParameterName, InputCertificateFilePasswordParameterName, InputCertificate, ContextParameterName); 

            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 21 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ContextParameterName));
            
            #line default
            #line hidden
            this.Write(".Log(string.Format(\"Protecting [{0}].\", ");
            
            #line 21 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OutputFilePathParameterName));
            
            #line default
            #line hidden
            this.Write("));\r\n\tusing (var outputStream = new System.IO.FileStream(");
            
            #line 22 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OutputFilePathParameterName));
            
            #line default
            #line hidden
            this.Write(", System.IO.FileMode.Create))\r\n\tusing (var ");
            
            #line 23 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(stamperPropertyName));
            
            #line default
            #line hidden
            this.Write(" = new iTextSharp.text.pdf.PdfStamper(");
            
            #line 23 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));
            
            #line default
            #line hidden
            this.Write(", outputStream))\r\n\t{\r\n\t\t");
            
            #line 25 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 AddProtection(stamperPropertyName, permissionsPropertyName, protectCertificatePropertyName); 
            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\nfinally\r\n{\r\n");
            
            #line 30 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 DisposePdfReader(readerPropertyName); 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 33 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"

private void AddProtection(string stamperPropertyName, string permissionsPropertyName, string protectCertificatePropertyName)
{
	if (ProtectProtection == AuthenticationType.None) { return; }

        
        #line default
        #line hidden
        
        #line 37 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write("int encryptionType = ");

        
        #line default
        #line hidden
        
        #line 38 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture((int)ProtectEncryption));

        
        #line default
        #line hidden
        
        #line 38 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 39 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 if (ProtectDontEncryptMetadata) { 
        
        #line default
        #line hidden
        
        #line 39 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write("encryptionType |= iTextSharp.text.pdf.PdfWriter.DO_NOT_ENCRYPT_METADATA;\r\n");

        
        #line default
        #line hidden
        
        #line 41 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 } 
        
        #line default
        #line hidden
        
        #line 41 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write("int ");

        
        #line default
        #line hidden
        
        #line 42 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(permissionsPropertyName));

        
        #line default
        #line hidden
        
        #line 42 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 43 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 AssignDocumentRestrictions(permissionsPropertyName); 
        
        #line default
        #line hidden
        
        #line 45 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 if (ProtectProtection == AuthenticationType.Certificate) { 
        
        #line default
        #line hidden
        
        #line 45 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write("System.Security.Cryptography.X509Certificates.X509Certificate2 ");

        
        #line default
        #line hidden
        
        #line 46 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(protectCertificatePropertyName));

        
        #line default
        #line hidden
        
        #line 46 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 47 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 AssignCertificateProperty(protectCertificatePropertyName, ProtectCertificateSource, ProtectCertificateFilePathParameterName, ProtectCertificateFilePasswordParameterName, ProtectCertificate); 
        
        #line default
        #line hidden
        
        #line 48 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(stamperPropertyName));

        
        #line default
        #line hidden
        
        #line 48 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(".SetEncryption(\r\n\t\tnew System.Collections.Generic.List<System.Security.Cryptograp" +
        "hy.X509Certificates.X509Certificate>{ ");

        
        #line default
        #line hidden
        
        #line 49 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(protectCertificatePropertyName));

        
        #line default
        #line hidden
        
        #line 49 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(" }\r\n\t\t\t.Select(cert => Org.BouncyCastle.Security.DotNetUtilities.FromX509Certific" +
        "ate(cert)).ToArray(),\r\n\t\tnew int[] { permissions },\r\n\t\tencryptionType);\r\n");

        
        #line default
        #line hidden
        
        #line 53 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 } else if (ProtectProtection == AuthenticationType.Password) { 
        
        #line default
        #line hidden
        
        #line 53 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write("string permissionsPassword;\r\n\t");

        
        #line default
        #line hidden
        
        #line 55 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 if (ProtectAddDocumentRestrictions) { 
        
        #line default
        #line hidden
        
        #line 55 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write("permissionsPassword = ");

        
        #line default
        #line hidden
        
        #line 56 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ProtectPermissionsPasswordParameterName));

        
        #line default
        #line hidden
        
        #line 56 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(";\r\n\t");

        
        #line default
        #line hidden
        
        #line 57 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 } else { 
        
        #line default
        #line hidden
        
        #line 57 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write("permissionsPassword = ");

        
        #line default
        #line hidden
        
        #line 58 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ProtectDocumentOpenPasswordParameterName));

        
        #line default
        #line hidden
        
        #line 58 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(";\r\n\t");

        
        #line default
        #line hidden
        
        #line 59 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 } 
        
        #line default
        #line hidden
        
        #line 60 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(stamperPropertyName));

        
        #line default
        #line hidden
        
        #line 60 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(".SetEncryption(\r\n\tencryptionType,\r\n\t");

        
        #line default
        #line hidden
        
        #line 62 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ProtectDocumentOpenPasswordParameterName));

        
        #line default
        #line hidden
        
        #line 62 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(",\r\n\tpermissionsPassword,\r\n\tpermissions);\r\n");

        
        #line default
        #line hidden
        
        #line 65 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 } 
        
        #line default
        #line hidden
        
        #line 66 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"

}

        
        #line default
        #line hidden
        
        #line 70 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 
private void AssignDocumentRestrictions(string permissionsPropertyName)
{

        
        #line default
        #line hidden
        
        #line 74 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 if (ProtectAddDocumentRestrictions) { 
        
        #line default
        #line hidden
        
        #line 75 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(permissionsPropertyName));

        
        #line default
        #line hidden
        
        #line 75 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(" = 0;\r\n");

        
        #line default
        #line hidden
        
        #line 76 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(permissionsPropertyName));

        
        #line default
        #line hidden
        
        #line 76 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(" |= ");

        
        #line default
        #line hidden
        
        #line 76 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture((int)ProtectAllowPrinting));

        
        #line default
        #line hidden
        
        #line 76 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 77 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(permissionsPropertyName));

        
        #line default
        #line hidden
        
        #line 77 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(" |= ");

        
        #line default
        #line hidden
        
        #line 77 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture((int)ProtectAllowChanges));

        
        #line default
        #line hidden
        
        #line 77 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(";\r\n\t");

        
        #line default
        #line hidden
        
        #line 78 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 if (ProtectAllowCopying) { 
        
        #line default
        #line hidden
        
        #line 79 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(permissionsPropertyName));

        
        #line default
        #line hidden
        
        #line 79 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(" |= iTextSharp.text.pdf.PdfWriter.ALLOW_COPY;\r\n\t");

        
        #line default
        #line hidden
        
        #line 80 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
	} 
        
        #line default
        #line hidden
        
        #line 80 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write("\t");

        
        #line default
        #line hidden
        
        #line 81 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 if (ProtectAllowScreenReaders) { 
        
        #line default
        #line hidden
        
        #line 82 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(permissionsPropertyName));

        
        #line default
        #line hidden
        
        #line 82 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(" |= iTextSharp.text.pdf.PdfWriter.ALLOW_SCREENREADERS;\r\n\t");

        
        #line default
        #line hidden
        
        #line 83 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
	} 
        
        #line default
        #line hidden
        
        #line 84 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
 } else { 
        
        #line default
        #line hidden
        
        #line 85 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(permissionsPropertyName));

        
        #line default
        #line hidden
        
        #line 85 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
this.Write(@" = 
	iTextSharp.text.pdf.PdfWriter.ALLOW_ASSEMBLY |
	iTextSharp.text.pdf.PdfWriter.ALLOW_COPY |
	iTextSharp.text.pdf.PdfWriter.ALLOW_DEGRADED_PRINTING |
	iTextSharp.text.pdf.PdfWriter.ALLOW_FILL_IN |
	iTextSharp.text.pdf.PdfWriter.ALLOW_MODIFY_ANNOTATIONS |
	iTextSharp.text.pdf.PdfWriter.ALLOW_MODIFY_CONTENTS |
	iTextSharp.text.pdf.PdfWriter.ALLOW_PRINTING |
	iTextSharp.text.pdf.PdfWriter.ALLOW_SCREENREADERS;
");

        
        #line default
        #line hidden
        
        #line 94 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"
	} 
        
        #line default
        #line hidden
        
        #line 95 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\ChangeProtectionTemplate.tt"

}

        
        #line default
        #line hidden
        
        #line 1 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

void AssignPdfReader(string readerPropertyName, AuthenticationType authenticationType, string filePropertyName, string passwordPropertyName,
	Twenty57.Linx.Components.Pdf.CertificateSource certificateSource, string certificateFilePathPropertyName, string certificateFilePasswordPropertyName, 
	Twenty57.Linx.Components.Pdf.StoredCertificate certificate,	string contextPropertyName)
{

        
        #line default
        #line hidden
        
        #line 6 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("if (string.IsNullOrEmpty(");

        
        #line default
        #line hidden
        
        #line 7 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 7 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("))\r\n\tthrow new ArgumentNullException(\"");

        
        #line default
        #line hidden
        
        #line 8 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 8 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("\");\r\nif (!System.IO.File.Exists(");

        
        #line default
        #line hidden
        
        #line 9 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 9 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("))\r\n\tthrow new System.IO.FileNotFoundException(string.Format(\"File [{0}] does not" +
        " exist.\", ");

        
        #line default
        #line hidden
        
        #line 10 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 10 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("));\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 12 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(contextPropertyName));

        
        #line default
        #line hidden
        
        #line 12 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(".Log(string.Format(\"Opening file [{0}].\", ");

        
        #line default
        #line hidden
        
        #line 12 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 12 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 13 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

	if (authenticationType == AuthenticationType.None)
	{

        
        #line default
        #line hidden
        
        #line 17 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 17 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" = new iTextSharp.text.pdf.PdfReader(");

        
        #line default
        #line hidden
        
        #line 17 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 17 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 18 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

	}
	else if (authenticationType == AuthenticationType.Password)
	{

        
        #line default
        #line hidden
        
        #line 23 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 23 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" = new iTextSharp.text.pdf.PdfReader(");

        
        #line default
        #line hidden
        
        #line 23 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 23 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(", System.Text.Encoding.UTF8.GetBytes(");

        
        #line default
        #line hidden
        
        #line 23 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(passwordPropertyName));

        
        #line default
        #line hidden
        
        #line 23 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 24 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

	}
	else if (authenticationType == AuthenticationType.Certificate)
	{
		string certificatePropertyName = "inputCertificate";

        
        #line default
        #line hidden
        
        #line 29 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("System.Security.Cryptography.X509Certificates.X509Certificate2 ");

        
        #line default
        #line hidden
        
        #line 30 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(certificatePropertyName));

        
        #line default
        #line hidden
        
        #line 30 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" = null;\r\n");

        
        #line default
        #line hidden
        
        #line 31 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
 AssignCertificateProperty(certificatePropertyName, certificateSource, certificateFilePathPropertyName, certificateFilePasswordPropertyName, certificate); 
        
        #line default
        #line hidden
        
        #line 31 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(@"if (!inputCertificate.HasPrivateKey)
	throw new NotSupportedException(""Certificate must have a private key."");

Org.BouncyCastle.X509.X509Certificate inputBouncyCertficate = Org.BouncyCastle.Security.DotNetUtilities.FromX509Certificate(inputCertificate);
Org.BouncyCastle.Crypto.AsymmetricCipherKeyPair inputKeyPair = Org.BouncyCastle.Security.DotNetUtilities.GetKeyPair(inputCertificate.PrivateKey);
");

        
        #line default
        #line hidden
        
        #line 37 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 37 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" = new iTextSharp.text.pdf.PdfReader(");

        
        #line default
        #line hidden
        
        #line 37 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 37 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(", inputBouncyCertficate, inputKeyPair.Private);\r\n");

        
        #line default
        #line hidden
        
        #line 38 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

	}
}

        
        #line default
        #line hidden
        
        #line 43 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

void DisposePdfReader(string readerPropertyName)
{

        
        #line default
        #line hidden
        
        #line 46 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("if (");

        
        #line default
        #line hidden
        
        #line 47 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 47 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" != null)\r\n\t");

        
        #line default
        #line hidden
        
        #line 48 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 48 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(".Dispose();\r\n");

        
        #line default
        #line hidden
        
        #line 49 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

}

        
        #line default
        #line hidden
        
        #line 53 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

void AssignCertificateProperty(string certificatePropertyName, Twenty57.Linx.Components.Pdf.CertificateSource certificateSource, 
	string certificateFilePathPropertyName, string certificateFilePasswordPropertyName, 
	Twenty57.Linx.Components.Pdf.StoredCertificate storedCertificatePropertyName)
{

        
        #line default
        #line hidden
        
        #line 59 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
	if (certificateSource == Twenty57.Linx.Components.Pdf.CertificateSource.File)	{ 
        
        #line default
        #line hidden
        
        #line 60 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(certificatePropertyName));

        
        #line default
        #line hidden
        
        #line 60 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" = new System.Security.Cryptography.X509Certificates.X509Certificate2(");

        
        #line default
        #line hidden
        
        #line 60 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(certificateFilePathPropertyName));

        
        #line default
        #line hidden
        
        #line 60 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 60 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(certificateFilePasswordPropertyName));

        
        #line default
        #line hidden
        
        #line 60 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(", System.Security.Cryptography.X509Certificates.X509KeyStorageFlags.Exportable);\r" +
        "\n");

        
        #line default
        #line hidden
        
        #line 61 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
 } else if (certificateSource == Twenty57.Linx.Components.Pdf.CertificateSource.Store) { 
        
        #line default
        #line hidden
        
        #line 62 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(certificatePropertyName));

        
        #line default
        #line hidden
        
        #line 62 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" = new Twenty57.Linx.Components.Pdf.StoredCertificate(\r\n\t");

        
        #line default
        #line hidden
        
        #line 63 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(Twenty57.Linx.Plugin.Common.CodeGeneration.CSharpUtilities.EnumAsString(storedCertificatePropertyName.StoreLocation)));

        
        #line default
        #line hidden
        
        #line 63 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(", \r\n\t");

        
        #line default
        #line hidden
        
        #line 64 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(Twenty57.Linx.Plugin.Common.CodeGeneration.CSharpUtilities.EnumAsString(storedCertificatePropertyName.StoreName)));

        
        #line default
        #line hidden
        
        #line 64 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(", \r\n\t\"");

        
        #line default
        #line hidden
        
        #line 65 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(storedCertificatePropertyName.ThumbPrint));

        
        #line default
        #line hidden
        
        #line 65 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("\").GetCertificate();\r\n");

        
        #line default
        #line hidden
        
        #line 66 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
	} 
        
        #line default
        #line hidden
        
        #line 67 "D:\Hg\Linx5Components\PDF\PDF-2455\Linx5.Components.PDF\src\Pdf\ChangeProtection\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    internal class ChangeProtectionTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
