// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Twenty57.Linx.Components.Pdf.ReadPdf.Templates
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    internal partial class ReadTemplate : ReadTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 3 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 
	string readerPropertyName = "reader";
	string outputPropertyName = "output"; 

            
            #line default
            #line hidden
            this.Write("\r\niTextSharp.text.pdf.PdfReader ");
            
            #line 8 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n\r\ntry\r\n{\r\n");
            
            #line 12 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 
AssignPdfReader(readerPropertyName, AuthenticationType, PdfFilePathParameterName, PdfPasswordParameterName, 
	CertificateSource, CertificateFilePathParameterName, CertificateFilePasswordParameterName, Certificate, ContextParameterName); 

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 17 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 if (HasOutput) { 
            
            #line default
            #line hidden
            this.Write("\tvar ");
            
            #line 18 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputPropertyName));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 18 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OutputTypeName));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 19 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 ReadTextValues(readerPropertyName, outputPropertyName); 
            
            #line default
            #line hidden
            
            #line 20 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 ReadFormDataValues(readerPropertyName, outputPropertyName); 
            
            #line default
            #line hidden
            
            #line 21 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 ReadSignatureValues(readerPropertyName, outputPropertyName); 
            
            #line default
            #line hidden
            this.Write("\treturn output;\r\n");
            
            #line 23 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\nfinally\r\n{\r\n");
            
            #line 27 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 DisposePdfReader(readerPropertyName); 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 30 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"

private void ReadTextValues(string readerPropertyName, string outputPropertyName)
{
	if (!ReadText) { return; }

        
        #line default
        #line hidden
        
        #line 35 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ContextParameterName));

        
        #line default
        #line hidden
        
        #line 35 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".Log(string.Format(\"Start reading text of [{0}].\", ");

        
        #line default
        #line hidden
        
        #line 35 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(PdfFilePathParameterName));

        
        #line default
        #line hidden
        
        #line 35 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write("));\r\nvar pageList = new System.Collections.Generic.List<string>();\r\n\r\nfor (int in" +
        "dex = 1; index <= ");

        
        #line default
        #line hidden
        
        #line 38 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 38 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".NumberOfPages; index++)\r\n{\t\r\n\tvar strategy = new Twenty57.Linx.Components.Pdf.Re" +
        "adPdf.Helpers.TopToBottomTextExtractionStrategy();\r\n\tpageList.Add(iTextSharp.tex" +
        "t.pdf.parser.PdfTextExtractor.GetTextFromPage(");

        
        #line default
        #line hidden
        
        #line 41 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 41 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(", index, strategy));\r\n}\r\n");

        
        #line default
        #line hidden
        
        #line 43 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 if (TextSplit == TextSplit.Never) { 
        
        #line default
        #line hidden
        
        #line 44 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(outputPropertyName));

        
        #line default
        #line hidden
        
        #line 44 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 44 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputTextPropertyName));

        
        #line default
        #line hidden
        
        #line 44 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = string.Join(Environment.NewLine, pageList);\r\n");

        
        #line default
        #line hidden
        
        #line 45 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 } else if (TextSplit == TextSplit.Page) { 
        
        #line default
        #line hidden
        
        #line 46 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(outputPropertyName));

        
        #line default
        #line hidden
        
        #line 46 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 46 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputTextPropertyName));

        
        #line default
        #line hidden
        
        #line 46 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = pageList;\r\n");

        
        #line default
        #line hidden
        
        #line 47 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 } 
        
        #line default
        #line hidden
        
        #line 48 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ContextParameterName));

        
        #line default
        #line hidden
        
        #line 48 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".Log(string.Format(\"Finished reading text of [{0}].\", ");

        
        #line default
        #line hidden
        
        #line 48 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(PdfFilePathParameterName));

        
        #line default
        #line hidden
        
        #line 48 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 49 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"

}

        
        #line default
        #line hidden
        
        #line 53 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"

private void ReadFormDataValues(string readerPropertyName, string outputPropertyName)
{
	if (!ReadFormData) { return; }

        
        #line default
        #line hidden
        
        #line 58 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ContextParameterName));

        
        #line default
        #line hidden
        
        #line 58 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".Log(string.Format(\"Start reading form data of [{0}].\", ");

        
        #line default
        #line hidden
        
        #line 58 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(PdfFilePathParameterName));

        
        #line default
        #line hidden
        
        #line 58 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write("));\r\niTextSharp.text.pdf.AcroFields form = ");

        
        #line default
        #line hidden
        
        #line 59 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 59 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".AcroFields;\r\nbool isXfaForm = form.Xfa.XfaPresent;\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 62 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 if (FormExtraction == FormExtraction.List) { 
        
        #line default
        #line hidden
        
        #line 62 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write("\tif (isXfaForm)\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 64 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(outputPropertyName));

        
        #line default
        #line hidden
        
        #line 64 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 64 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputFormDataListPropertyName));

        
        #line default
        #line hidden
        
        #line 64 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = form.Xfa.DatasetsSom.Name2Node.ToDictionary(field => field.Key, field => field" +
        ".Value.InnerText).ToList();\r\n\telse\r\n\t");

        
        #line default
        #line hidden
        
        #line 66 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(outputPropertyName));

        
        #line default
        #line hidden
        
        #line 66 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 66 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputFormDataListPropertyName));

        
        #line default
        #line hidden
        
        #line 66 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = form.Fields.Keys.ToDictionary(key => key, key => form.GetField(key)).ToList();" +
        "\r\n");

        
        #line default
        #line hidden
        
        #line 67 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 } else if (FormExtraction == FormExtraction.CustomType || FormExtraction == FormExtraction.Infer) { 
        
        #line default
        #line hidden
        
        #line 67 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write("var result = Activator.CreateInstance<");

        
        #line default
        #line hidden
        
        #line 68 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputFormDataTypeName));

        
        #line default
        #line hidden
        
        #line 68 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(@">();
System.Collections.Generic.Dictionary<string, string> fields = new Dictionary<string,string>();
if (isXfaForm)
	fields = form.Xfa.DatasetsSom.Name2Node.ToDictionary(field => Twenty57.Linx.Plugin.Common.Names.GetValidName(field.Key), field => field.Value.InnerText);
else
	fields = form.Fields.Keys.ToDictionary(key => Twenty57.Linx.Plugin.Common.Names.GetValidName(key), key => form.GetField(key));

foreach (System.Reflection.PropertyInfo property in typeof(");

        
        #line default
        #line hidden
        
        #line 75 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputFormDataTypeName));

        
        #line default
        #line hidden
        
        #line 75 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(@").GetProperties())
{
	if (!fields.ContainsKey(property.Name))
		throw new Exception(string.Format(""Could not find a form field named [{0}]"", property.Name));

	string fieldValue = fields[property.Name];
	if (property.PropertyType.IsAssignableFrom(fieldValue.GetType()))
		property.SetValue(result, fieldValue);
	else
	{
		System.ComponentModel.TypeConverter typeConverter = System.ComponentModel.TypeDescriptor.GetConverter(property.PropertyType);
		if (typeConverter == null || !typeConverter.CanConvertFrom(fieldValue.GetType()))
			throw new Exception(string.Format(""Could not convert form field [{0}] with value [{1}] to type [{2}]."", 
				property.Name, fieldValue, property.PropertyType.Name));
			
		property.SetValue(result, typeConverter.ConvertFrom(fieldValue));
	}
}
");

        
        #line default
        #line hidden
        
        #line 93 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(outputPropertyName));

        
        #line default
        #line hidden
        
        #line 93 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 93 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputFormDataPropertyName));

        
        #line default
        #line hidden
        
        #line 93 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = result;\r\n");

        
        #line default
        #line hidden
        
        #line 94 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
 } 
        
        #line default
        #line hidden
        
        #line 95 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ContextParameterName));

        
        #line default
        #line hidden
        
        #line 95 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".Log(string.Format(\"Finished reading textform data of [{0}].\", ");

        
        #line default
        #line hidden
        
        #line 95 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(PdfFilePathParameterName));

        
        #line default
        #line hidden
        
        #line 95 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 96 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"

}

        
        #line default
        #line hidden
        
        #line 100 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"

private void ReadSignatureValues(string readerPropertyName, string outputPropertyName)
{
	if (!ReadSignature) { return;	}

        
        #line default
        #line hidden
        
        #line 105 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ContextParameterName));

        
        #line default
        #line hidden
        
        #line 105 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".Log(string.Format(\"Start reading signature of [{0}].\", ");

        
        #line default
        #line hidden
        
        #line 105 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(PdfFilePathParameterName));

        
        #line default
        #line hidden
        
        #line 105 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write("));\r\niTextSharp.text.pdf.AcroFields fields = ");

        
        #line default
        #line hidden
        
        #line 106 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 106 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".AcroFields;\r\nvar signatures = new ");

        
        #line default
        #line hidden
        
        #line 107 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputSignaturesTypeName));

        
        #line default
        #line hidden
        
        #line 107 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write("();\r\nsignatures.");

        
        #line default
        #line hidden
        
        #line 108 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputAllSignaturesPropertyName));

        
        #line default
        #line hidden
        
        #line 108 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = new System.Collections.Generic.List<");

        
        #line default
        #line hidden
        
        #line 108 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputLatestSignatureTypeName));

        
        #line default
        #line hidden
        
        #line 108 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(">(); \r\nforeach (string name in fields.GetSignatureNames())\r\n{\r\n\tiTextSharp.text.p" +
        "df.security.PdfPKCS7 pk = fields.VerifySignature(name);\r\n\r\n\tvar signature = new " +
        "");

        
        #line default
        #line hidden
        
        #line 113 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputLatestSignatureTypeName));

        
        #line default
        #line hidden
        
        #line 113 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write("();\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 114 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputSignedByName));

        
        #line default
        #line hidden
        
        #line 114 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = pk.SignName ?? iTextSharp.text.pdf.security.CertificateInfo.GetSubjectFields(p" +
        "k.SigningCertificate).GetField(\"CN\");\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 115 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputSignedAtName));

        
        #line default
        #line hidden
        
        #line 115 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = pk.Location;\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 116 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputReasonName));

        
        #line default
        #line hidden
        
        #line 116 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = pk.Reason;\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 117 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputSignedOnName));

        
        #line default
        #line hidden
        
        #line 117 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = pk.SignDate;\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 118 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputUnmodifiedName));

        
        #line default
        #line hidden
        
        #line 118 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = pk.Verify();\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 119 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputSignedRevisionName));

        
        #line default
        #line hidden
        
        #line 119 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = pk.SigningInfoVersion;\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 120 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputIsLatestRevisionName));

        
        #line default
        #line hidden
        
        #line 120 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(@" = (pk.SigningInfoVersion == fields.TotalRevisions);

	var certificate = new System.Security.Cryptography.X509Certificates.X509Certificate2(Org.BouncyCastle.Security.DotNetUtilities.ToX509Certificate(pk.SigningCertificate));
	var chain = new System.Security.Cryptography.X509Certificates.X509Chain();
	chain.Build(certificate);
	signature.");

        
        #line default
        #line hidden
        
        #line 125 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputVerifiedName));

        
        #line default
        #line hidden
        
        #line 125 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = certificate.Verify();\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 126 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputVerificationMessageName));

        
        #line default
        #line hidden
        
        #line 126 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = string.Join(\", \", chain.ChainStatus.Select(cs => cs.StatusInformation).Where(s" +
        "i => !string.IsNullOrEmpty(si)).ToArray());\r\n\r\n\tsignatures.");

        
        #line default
        #line hidden
        
        #line 128 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputAllSignaturesPropertyName));

        
        #line default
        #line hidden
        
        #line 128 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".Add(signature);\r\n}\r\n\r\nsignatures.");

        
        #line default
        #line hidden
        
        #line 131 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputIsSignedPropertyName));

        
        #line default
        #line hidden
        
        #line 131 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = signatures.");

        
        #line default
        #line hidden
        
        #line 131 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputAllSignaturesPropertyName));

        
        #line default
        #line hidden
        
        #line 131 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".Any();\r\nif (signatures.");

        
        #line default
        #line hidden
        
        #line 132 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputIsSignedPropertyName));

        
        #line default
        #line hidden
        
        #line 132 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(")\r\n\tsignatures.");

        
        #line default
        #line hidden
        
        #line 133 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputLatestSignaturePropertyName));

        
        #line default
        #line hidden
        
        #line 133 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = signatures.");

        
        #line default
        #line hidden
        
        #line 133 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputAllSignaturesPropertyName));

        
        #line default
        #line hidden
        
        #line 133 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".OrderByDescending(sig => sig.SignedOn).FirstOrDefault();\r\nelse\r\n{\r\n\tvar signatur" +
        "e = new ");

        
        #line default
        #line hidden
        
        #line 136 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputLatestSignatureTypeName));

        
        #line default
        #line hidden
        
        #line 136 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write("();\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 137 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputSignedByName));

        
        #line default
        #line hidden
        
        #line 137 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = string.Empty;\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 138 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputSignedAtName));

        
        #line default
        #line hidden
        
        #line 138 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = string.Empty;\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 139 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputReasonName));

        
        #line default
        #line hidden
        
        #line 139 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = string.Empty;\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 140 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputSignedOnName));

        
        #line default
        #line hidden
        
        #line 140 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = DateTime.MinValue;\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 141 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputUnmodifiedName));

        
        #line default
        #line hidden
        
        #line 141 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = true;\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 142 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputSignedRevisionName));

        
        #line default
        #line hidden
        
        #line 142 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = 0;\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 143 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputIsLatestRevisionName));

        
        #line default
        #line hidden
        
        #line 143 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = true;\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 144 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputVerifiedName));

        
        #line default
        #line hidden
        
        #line 144 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = false;\r\n\tsignature.");

        
        #line default
        #line hidden
        
        #line 145 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputVerificationMessageName));

        
        #line default
        #line hidden
        
        #line 145 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = \"No certificate found.\";\r\n\tsignatures.");

        
        #line default
        #line hidden
        
        #line 146 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputLatestSignaturePropertyName));

        
        #line default
        #line hidden
        
        #line 146 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = signature;\r\n}\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 149 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(outputPropertyName));

        
        #line default
        #line hidden
        
        #line 149 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 149 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(OutputSignaturesPropertyName));

        
        #line default
        #line hidden
        
        #line 149 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(" = signatures;\r\n");

        
        #line default
        #line hidden
        
        #line 150 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ContextParameterName));

        
        #line default
        #line hidden
        
        #line 150 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(".Log(string.Format(\"Finished reading signature of [{0}].\", ");

        
        #line default
        #line hidden
        
        #line 150 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(PdfFilePathParameterName));

        
        #line default
        #line hidden
        
        #line 150 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 151 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\ReadTemplate.tt"

}

        
        #line default
        #line hidden
        
        #line 1 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

void AssignPdfReader(string readerPropertyName, AuthenticationType authenticationType, string filePropertyName, string passwordPropertyName,
	Twenty57.Linx.Components.Pdf.CertificateSource certificateSource, string certificateFilePathPropertyName, string certificateFilePasswordPropertyName, 
	Twenty57.Linx.Components.Pdf.StoredCertificate certificate,	string contextPropertyName)
{

        
        #line default
        #line hidden
        
        #line 6 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("if (string.IsNullOrEmpty(");

        
        #line default
        #line hidden
        
        #line 7 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 7 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("))\r\n\tthrow new ArgumentNullException(\"");

        
        #line default
        #line hidden
        
        #line 8 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 8 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("\");\r\nif (!System.IO.File.Exists(");

        
        #line default
        #line hidden
        
        #line 9 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 9 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("))\r\n\tthrow new System.IO.FileNotFoundException(string.Format(\"File [{0}] does not" +
        " exist.\", ");

        
        #line default
        #line hidden
        
        #line 10 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 10 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("));\r\n\r\n");

        
        #line default
        #line hidden
        
        #line 12 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(contextPropertyName));

        
        #line default
        #line hidden
        
        #line 12 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(".Log(string.Format(\"Opening file [{0}].\", ");

        
        #line default
        #line hidden
        
        #line 12 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 12 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 13 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

	if (authenticationType == AuthenticationType.None)
	{

        
        #line default
        #line hidden
        
        #line 17 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 17 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" = new iTextSharp.text.pdf.PdfReader(");

        
        #line default
        #line hidden
        
        #line 17 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 17 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(");\r\n");

        
        #line default
        #line hidden
        
        #line 18 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

	}
	else if (authenticationType == AuthenticationType.Password)
	{

        
        #line default
        #line hidden
        
        #line 23 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 23 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" = new iTextSharp.text.pdf.PdfReader(");

        
        #line default
        #line hidden
        
        #line 23 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 23 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(", System.Text.Encoding.UTF8.GetBytes(");

        
        #line default
        #line hidden
        
        #line 23 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(passwordPropertyName));

        
        #line default
        #line hidden
        
        #line 23 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("));\r\n");

        
        #line default
        #line hidden
        
        #line 24 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

	}
	else if (authenticationType == AuthenticationType.Certificate)
	{
		string certificatePropertyName = "inputCertificate";

        
        #line default
        #line hidden
        
        #line 29 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("System.Security.Cryptography.X509Certificates.X509Certificate2 ");

        
        #line default
        #line hidden
        
        #line 30 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(certificatePropertyName));

        
        #line default
        #line hidden
        
        #line 30 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" = null;\r\n");

        
        #line default
        #line hidden
        
        #line 31 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
 AssignCertificateProperty(certificatePropertyName, certificateSource, certificateFilePathPropertyName, certificateFilePasswordPropertyName, certificate); 
        
        #line default
        #line hidden
        
        #line 31 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(@"if (!inputCertificate.HasPrivateKey)
	throw new NotSupportedException(""Certificate must have a private key."");

Org.BouncyCastle.X509.X509Certificate inputBouncyCertficate = Org.BouncyCastle.Security.DotNetUtilities.FromX509Certificate(inputCertificate);
Org.BouncyCastle.Crypto.AsymmetricCipherKeyPair inputKeyPair = Org.BouncyCastle.Security.DotNetUtilities.GetKeyPair(inputCertificate.PrivateKey);
");

        
        #line default
        #line hidden
        
        #line 37 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 37 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" = new iTextSharp.text.pdf.PdfReader(");

        
        #line default
        #line hidden
        
        #line 37 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(filePropertyName));

        
        #line default
        #line hidden
        
        #line 37 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(", inputBouncyCertficate, inputKeyPair.Private);\r\n");

        
        #line default
        #line hidden
        
        #line 38 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

	}
}

        
        #line default
        #line hidden
        
        #line 43 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

void DisposePdfReader(string readerPropertyName)
{

        
        #line default
        #line hidden
        
        #line 46 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("if (");

        
        #line default
        #line hidden
        
        #line 47 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 47 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" != null)\r\n\t");

        
        #line default
        #line hidden
        
        #line 48 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(readerPropertyName));

        
        #line default
        #line hidden
        
        #line 48 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(".Dispose();\r\n");

        
        #line default
        #line hidden
        
        #line 49 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

}

        
        #line default
        #line hidden
        
        #line 53 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

void AssignCertificateProperty(string certificatePropertyName, Twenty57.Linx.Components.Pdf.CertificateSource certificateSource, 
	string certificateFilePathPropertyName, string certificateFilePasswordPropertyName, 
	Twenty57.Linx.Components.Pdf.StoredCertificate storedCertificatePropertyName)
{

        
        #line default
        #line hidden
        
        #line 59 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
	if (certificateSource == Twenty57.Linx.Components.Pdf.CertificateSource.File)	{ 
        
        #line default
        #line hidden
        
        #line 60 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(certificatePropertyName));

        
        #line default
        #line hidden
        
        #line 60 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" = new System.Security.Cryptography.X509Certificates.X509Certificate2(");

        
        #line default
        #line hidden
        
        #line 60 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(certificateFilePathPropertyName));

        
        #line default
        #line hidden
        
        #line 60 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 60 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(certificateFilePasswordPropertyName));

        
        #line default
        #line hidden
        
        #line 60 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(", System.Security.Cryptography.X509Certificates.X509KeyStorageFlags.Exportable);\r" +
        "\n");

        
        #line default
        #line hidden
        
        #line 61 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
 } else if (certificateSource == Twenty57.Linx.Components.Pdf.CertificateSource.Store) { 
        
        #line default
        #line hidden
        
        #line 62 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(certificatePropertyName));

        
        #line default
        #line hidden
        
        #line 62 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(" = new Twenty57.Linx.Components.Pdf.StoredCertificate(\r\n\t");

        
        #line default
        #line hidden
        
        #line 63 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(Twenty57.Linx.Plugin.Common.CodeGeneration.CSharpUtilities.EnumAsString(storedCertificatePropertyName.StoreLocation)));

        
        #line default
        #line hidden
        
        #line 63 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(", \r\n\t");

        
        #line default
        #line hidden
        
        #line 64 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(Twenty57.Linx.Plugin.Common.CodeGeneration.CSharpUtilities.EnumAsString(storedCertificatePropertyName.StoreName)));

        
        #line default
        #line hidden
        
        #line 64 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(", \r\n\t\"");

        
        #line default
        #line hidden
        
        #line 65 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write(this.ToStringHelper.ToStringWithCulture(storedCertificatePropertyName.ThumbPrint));

        
        #line default
        #line hidden
        
        #line 65 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
this.Write("\").GetCertificate();\r\n");

        
        #line default
        #line hidden
        
        #line 66 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"
	} 
        
        #line default
        #line hidden
        
        #line 67 "C:\HG\linx5-components-pdf\src\Pdf\ReadPdf\Templates\..\..\Common\ManagePdfReaderTemplate.t4"

}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    internal class ReadTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
